-- =================================================================
-- UHWF PORTAL DATABASE - FULL SQL FILE
-- Includes: ENUMs, tables, relationships, sample data
-- Ready for PostgreSQL / pgAdmin
-- =================================================================

-- 1. ENUM for account roles
CREATE TYPE public.account_type AS ENUM
( 'citizen', 'employee', 'student','member','admin');

-- 2. Table: account (users)
CREATE TABLE public.account (
    account_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_firstname CHARACTER VARYING NOT NULL,
    account_lastname CHARACTER VARYING NOT NULL,
    account_email CHARACTER VARYING UNIQUE NOT NULL,
    account_password CHARACTER VARYING NOT NULL,
     account_type account_type NOT NULL DEFAULT 'citizen'::account_type,
);

-- student table which is relationship with account table.
CREATE TABLE public.students (
    student_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    account_id INT NOT NULL,

    registration_no VARCHAR(50) UNIQUE NOT NULL,
    programme       VARCHAR(150) NOT NULL,
    year_level       INT NOT NULL,
    semester         INT NOT NULL,

    phone            VARCHAR(30),
    status           VARCHAR(30) DEFAULT 'Active',

    profile_image    VARCHAR(255),

    admission_date   DATE DEFAULT CURRENT_DATE,
    created_at       TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_student_account
        FOREIGN KEY (account_id)
        REFERENCES public.account(account_id)
        ON DELETE CASCADE
);
--  student table end here.

-- 3. Employee table (all additional employee details + link to account)
CREATE TABLE public.employees (
    employee_id SERIAL PRIMARY KEY,
    account_id INT UNIQUE NOT NULL,
    employee_code VARCHAR(20) UNIQUE NOT NULL,
    phone_numberVARCHAR(20) UNIQUE,           -- made optional (NULL allowed)
    department VARCHAR(100),
    position VARCHAR(100),
    hire_date DATE,
    profile_image   TEXT DEFAULT '/uploads/employees/default.png',
    status VARCHAR(20) DEFAULT 'active',
        CHECK (status IN ('active', 'inactive', 'suspended', 'terminated')),
    created_at     TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    -- Foreign key constraint (no semicolon here!)
    CONSTRAINT fk_employee_account
        FOREIGN KEY (account_id)
        REFERENCES public.account(account_id)
        ON DELETE CASCADE
);
 --employees table end here

-- 3. Table: document_category
CREATE TABLE public.document_category (
    category_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_name CHARACTER VARYING NOT NULL
);

-- 4. Table: document
CREATE TABLE public.document (
    document_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_title CHARACTER VARYING NOT NULL,
    document_description TEXT,
    document_file CHARACTER VARYING NOT NULL,
    version_number INT DEFAULT 1 NOT NULL,
    status CHARACTER VARYING DEFAULT 'submitted' NOT NULL,
    uploaded_by INT NOT NULL,
    category_id INT NOT NULL
);

-- 5. Relationships: document -> account & category
ALTER TABLE public.document
ADD CONSTRAINT fk_document_account
FOREIGN KEY (uploaded_by)
REFERENCES public.account (account_id)
ON UPDATE CASCADE;

ALTER TABLE public.document
ADD CONSTRAINT fk_document_category
FOREIGN KEY (category_id)
REFERENCES public.document_category (category_id)
ON UPDATE CASCADE;

-- Drop the old table if it exists (only if you have no important data!)
-- DROP TABLE IF EXISTS public.member CASCADE;

-- Create the corrected member table
CREATE TABLE public.member (
    member_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_firstname CHARACTER VARYING NOT NULL,
    member_lastname CHARACTER VARYING NOT NULL,
    member_email CHARACTER VARYING UNIQUE NOT NULL,
    member_phone CHARACTER VARYING UNIQUE,
    member_address TEXT,
    member_profile_image VARCHAR(255),                    -- for photo
    membership_number CHARACTER VARYING,           -- added: optional
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    account_type CHARACTER VARYING DEFAULT 'member'
    -- REMOVED: member_password (NOT NULL) → because form doesn't collect it
);

-- Indexes for performance
CREATE INDEX IF NOT EXISTS idx_member_email ON public.member(member_email);
CREATE INDEX IF NOT EXISTS idx_member_name ON public.member(member_firstname, member_lastname);

-- employee table.

CREATE TABLE employees (
    employee_id SERIAL PRIMARY KEY,
    account_id INT UNIQUE NOT NULL,
    employee_code VARCHAR(20) UNIQUE NOT NULL,
    department VARCHAR(100),
    position VARCHAR(100),
    hire_date DATE,
    profile_image_url TEXT NOT NULL,   -- ← MUST HAVE image (NOT NULL)
    status VARCHAR(20) DEFAULT 'active',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    
    CONSTRAINT fk_employee_account
        FOREIGN KEY (account_id)
        REFERENCES account(account_id)
        ON DELETE CASCADE
);

-- 6. Table: payment
CREATE TABLE public.payment (
    payment_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id INT NOT NULL,
    payment_amount NUMERIC(9,2) NOT NULL,
    payment_method CHARACTER VARYING NOT NULL, -- mpesa, airtel, visa
    payment_type CHARACTER VARYING NOT NULL,   -- membership, donation, event
    payment_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    receipt_number CHARACTER VARYING NOT NULL
);

-- 7. Relationship: payment -> account
ALTER TABLE public.payment
ADD CONSTRAINT fk_payment_account
FOREIGN KEY (account_id)
REFERENCES public.account (account_id)
ON UPDATE CASCADE;

-- 8. Table: forum_category
CREATE TABLE public.forum_category (
    forum_category_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    forum_category_name CHARACTER VARYING NOT NULL
);

-- 9. Table: forum_post
CREATE TABLE public.forum_post (
    post_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_title CHARACTER VARYING NOT NULL,
    post_body TEXT NOT NULL,
    account_id INT NOT NULL,
    forum_category_id INT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 10. Relationships: forum_post -> account & category
ALTER TABLE public.forum_post
ADD CONSTRAINT fk_forum_post_account
FOREIGN KEY (account_id)
REFERENCES public.account (account_id)
ON UPDATE CASCADE;

ALTER TABLE public.forum_post
ADD CONSTRAINT fk_forum_post_category
FOREIGN KEY (forum_category_id)
REFERENCES public.forum_category (forum_category_id)
ON UPDATE CASCADE;

-- 11. Table: forum_reply
CREATE TABLE public.forum_reply (
    reply_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reply_body TEXT NOT NULL,
    post_id INT NOT NULL,
    account_id INT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 12. Relationships: forum_reply -> post & account
ALTER TABLE public.forum_reply
ADD CONSTRAINT fk_forum_reply_post
FOREIGN KEY (post_id)
REFERENCES public.forum_post (post_id)
ON UPDATE CASCADE;

ALTER TABLE public.forum_reply
ADD CONSTRAINT fk_forum_reply_account
FOREIGN KEY (account_id)
REFERENCES public.account (account_id)
ON UPDATE CASCADE;

--  FOR CONTACT PAGE
CREATE TABLE public.contact_messages (
    id SERIAL PRIMARY KEY,
    firstname VARCHAR(100) NOT NULL,
    lastname VARCHAR(100) NOT NULL,
    email VARCHAR(150) NOT NULL,
    message TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    status VARCHAR(20) DEFAULT 'new'  -- e.g., 'new', 'read', 'replied'
);


-- News
CREATE TABLE IF NOT EXISTS public.news (
  news_id       SERIAL PRIMARY KEY,
  title         VARCHAR(255) NOT NULL,
  description   TEXT NOT NULL,
  profile_image     VARCHAR(255),
  news_date     DATE DEFAULT CURRENT_DATE,
  created_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  created_by    INTEGER REFERENCES public.account(account_id),
  is_active     BOOLEAN DEFAULT TRUE
);

-- Events
CREATE TABLE IF NOT EXISTS public.events (
  event_id      SERIAL PRIMARY KEY,
  title         VARCHAR(255) NOT NULL,
  description   TEXT,
  event_date    DATE NOT NULL,
  location      VARCHAR(255),
  image_url     VARCHAR(255),
  created_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  created_by    INTEGER REFERENCES public.account(account_id),
  is_active     BOOLEAN DEFAULT TRUE
);


-- video table
CREATE TABLE IF NOT EXISTS public.videos (
  video_id          SERIAL PRIMARY KEY,
  title             VARCHAR(255) NOT NULL,
  description       TEXT,
  youtube_url       VARCHAR(500) NOT NULL,        -- Full YouTube link or embed code
  youtube_id        VARCHAR(20),                  -- Extracted video ID (e.g. dQw4w9wgxcq)
  thumbnail         VARCHAR(255),                 -- Optional custom thumbnail
  category          VARCHAR(100) DEFAULT 'General',
  is_active         BOOLEAN DEFAULT TRUE,
  created_by        INTEGER REFERENCES public.account(account_id),
  created_at        TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- password reset
CREATE TABLE IF NOT EXISTS public.password_resets (
  id SERIAL PRIMARY KEY,
  email VARCHAR(255) NOT NULL,
  token VARCHAR(255) NOT NULL UNIQUE,
  expires_at TIMESTAMP NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
 
--  job opening table
CREATE TABLE public.job_openings (
    id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    department_name VARCHAR(255) NOT NULL,
    job_title VARCHAR(255) NOT NULL,
    number_of_positions INT NOT NULL DEFAULT 1,
    qualifications JSONB NOT NULL,
    experience TEXT NOT NULL,
    posted_by INT NOT NULL,
    posted_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    status TEXT CHECK (status IN ('active', 'inactive')) DEFAULT 'active',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Tasks table
CREATE TABLE IF NOT EXISTS public.tasks (
  task_id        SERIAL PRIMARY KEY,
  title          VARCHAR(255) NOT NULL,
  description    TEXT,
  assigned_to    INTEGER REFERENCES public.account(account_id) ON DELETE CASCADE,
  assigned_by    INTEGER REFERENCES public.account(account_id),
  priority       VARCHAR(20)  DEFAULT 'medium',
  status         VARCHAR(30)  DEFAULT 'pending',
  due_date       DATE,
  created_at     TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Task Reports
CREATE TABLE IF NOT EXISTS public.task_reports (
  report_id      SERIAL PRIMARY KEY,
  task_id        INTEGER REFERENCES public.tasks(task_id) ON DELETE CASCADE,
  submitted_by   INTEGER REFERENCES public.account(account_id),
  report_text    TEXT NOT NULL,
  submitted_at   TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Admin Comments on Reports
CREATE TABLE IF NOT EXISTS public.report_comments (
  comment_id     SERIAL PRIMARY KEY,
  report_id      INTEGER REFERENCES public.task_reports(report_id) ON DELETE CASCADE,
  commented_by   INTEGER REFERENCES public.account(account_id),
  comment_text   TEXT NOT NULL,
  created_at     TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Notifications for employees
CREATE TABLE IF NOT EXISTS public.notifications (
  notification_id SERIAL PRIMARY KEY,
  user_id         INTEGER REFERENCES public.account(account_id) ON DELETE CASCADE,
  message         TEXT NOT NULL,
  link            VARCHAR(500),
  is_read         BOOLEAN   DEFAULT FALSE,
  created_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);