-- =================================================================
-- UHWF PORTAL DATABASE - FULL SQL FILE
-- Includes: ENUMs, tables, relationships, sample data
-- Ready for PostgreSQL / pgAdmin
-- =================================================================

-- 1. ENUM for account roles
CREATE TYPE public.account_type AS ENUM
( 'citizen', 'employee', 'student','member','admin');

-- 2. Table: account (users)
CREATE TABLE public.account (
    account_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_firstname CHARACTER VARYING NOT NULL,
    account_lastname CHARACTER VARYING NOT NULL,
    account_email CHARACTER VARYING UNIQUE NOT NULL,
    account_password CHARACTER VARYING NOT NULL,
     account_type account_type NOT NULL DEFAULT 'citizen'::account_type,
);

-- 3. Table: document_category
CREATE TABLE public.document_category (
    category_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_name CHARACTER VARYING NOT NULL
);

-- 4. Table: document
CREATE TABLE public.document (
    document_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_title CHARACTER VARYING NOT NULL,
    document_description TEXT,
    document_file CHARACTER VARYING NOT NULL,
    version_number INT DEFAULT 1 NOT NULL,
    status CHARACTER VARYING DEFAULT 'submitted' NOT NULL,
    uploaded_by INT NOT NULL,
    category_id INT NOT NULL
);

-- 5. Relationships: document -> account & category
ALTER TABLE public.document
ADD CONSTRAINT fk_document_account
FOREIGN KEY (uploaded_by)
REFERENCES public.account (account_id)
ON UPDATE CASCADE;

ALTER TABLE public.document
ADD CONSTRAINT fk_document_category
FOREIGN KEY (category_id)
REFERENCES public.document_category (category_id)
ON UPDATE CASCADE;

-- Drop the old table if it exists (only if you have no important data!)
-- DROP TABLE IF EXISTS public.member CASCADE;

-- Create the corrected member table
CREATE TABLE public.member (
    member_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_firstname CHARACTER VARYING NOT NULL,
    member_lastname CHARACTER VARYING NOT NULL,
    member_email CHARACTER VARYING UNIQUE NOT NULL,
    member_phone CHARACTER VARYING UNIQUE,
    member_address TEXT,
    member_profile_image VARCHAR(255),                    -- for photo
    membership_number CHARACTER VARYING,           -- added: optional
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    account_type CHARACTER VARYING DEFAULT 'member'
    -- REMOVED: member_password (NOT NULL) → because form doesn't collect it
);

-- Indexes for performance
CREATE INDEX IF NOT EXISTS idx_member_email ON public.member(member_email);
CREATE INDEX IF NOT EXISTS idx_member_name ON public.member(member_firstname, member_lastname);

-- 6. Table: payment
CREATE TABLE public.payment (
    payment_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id INT NOT NULL,
    payment_amount NUMERIC(9,2) NOT NULL,
    payment_method CHARACTER VARYING NOT NULL, -- mpesa, airtel, visa
    payment_type CHARACTER VARYING NOT NULL,   -- membership, donation, event
    payment_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    receipt_number CHARACTER VARYING NOT NULL
);

-- 7. Relationship: payment -> account
ALTER TABLE public.payment
ADD CONSTRAINT fk_payment_account
FOREIGN KEY (account_id)
REFERENCES public.account (account_id)
ON UPDATE CASCADE;

-- 8. Table: forum_category
CREATE TABLE public.forum_category (
    forum_category_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    forum_category_name CHARACTER VARYING NOT NULL
);

-- 9. Table: forum_post
CREATE TABLE public.forum_post (
    post_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_title CHARACTER VARYING NOT NULL,
    post_body TEXT NOT NULL,
    account_id INT NOT NULL,
    forum_category_id INT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 10. Relationships: forum_post -> account & category
ALTER TABLE public.forum_post
ADD CONSTRAINT fk_forum_post_account
FOREIGN KEY (account_id)
REFERENCES public.account (account_id)
ON UPDATE CASCADE;

ALTER TABLE public.forum_post
ADD CONSTRAINT fk_forum_post_category
FOREIGN KEY (forum_category_id)
REFERENCES public.forum_category (forum_category_id)
ON UPDATE CASCADE;

-- 11. Table: forum_reply
CREATE TABLE public.forum_reply (
    reply_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reply_body TEXT NOT NULL,
    post_id INT NOT NULL,
    account_id INT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 12. Relationships: forum_reply -> post & account
ALTER TABLE public.forum_reply
ADD CONSTRAINT fk_forum_reply_post
FOREIGN KEY (post_id)
REFERENCES public.forum_post (post_id)
ON UPDATE CASCADE;

ALTER TABLE public.forum_reply
ADD CONSTRAINT fk_forum_reply_account
FOREIGN KEY (account_id)
REFERENCES public.account (account_id)
ON UPDATE CASCADE;

-- =================================================================
-- SAMPLE DATA
-- =================================================================

-- Sample Accounts
INSERT INTO public.account (account_firstname, account_lastname, account_email, account_password, account_type)
VALUES
('Alice', 'Mwanza', 'alice.mwanza@uhwf.org', 'hashedpassword1', 'member'),
('Bob', 'Kibaki', 'bob.kibaki@uhwf.org', 'hashedpassword2', 'citizen'),
('Catherine', 'Nyerere', 'catherine.nyerere@uhwf.org', 'hashedpassword3', 'student'),
('David', 'Mwinyi', 'david.mwinyi@uhwf.org', 'hashedpassword4', 'employee'),
('Eve', 'Lema', 'eve.lema@uhwf.org', 'hashedpassword5', 'admin');

-- Sample Document Categories
INSERT INTO public.document_category (category_name)
VALUES
('research'),
('policy'),
('dataset'),
('assignment'),
('project');

-- Sample Documents
INSERT INTO public.document (document_title, document_description, document_file, version_number, status, uploaded_by, category_id)
VALUES
('Climate Change Study', 'A research report on climate patterns in Tanzania.', '/documents/climate.pdf', 1, 'submitted', 1, 1),
('Community Health Policy', 'Policy document for local community health programs.', '/documents/health_policy.pdf', 1, 'approved', 4, 2),
('Soil Dataset', 'CSV dataset of soil types collected in Iringa.', '/documents/soil_data.csv', 1, 'reviewed', 3, 3),
('Student Assignment 1', 'Assignment submission for environmental studies.', '/documents/assignment1.docx', 1, 'submitted', 3, 4);

-- Sample Payments
INSERT INTO public.payment (account_id, payment_amount, payment_method, payment_type, receipt_number)
VALUES
(2, 50.00, 'mpesa', 'membership', 'RCPT1001'),
(2, 30.00, 'visa', 'event', 'RCPT1002'),
(1, 100.00, 'airtel', 'donation', 'RCPT1003');

-- Sample Forum Categories
INSERT INTO public.forum_category (forum_category_name)
VALUES
('research'),
('policy'),
('community'),
('student corner');

-- Sample Forum Posts
INSERT INTO public.forum_post (post_title, post_body, account_id, forum_category_id)
VALUES
('Climate Research Findings', 'Sharing the latest research on local climate patterns.', 1, 1),
('Health Policy Update', 'New updates in the community health policy.', 4, 2),
('Community Meeting', 'Discussion on upcoming community events.', 2, 3),
('Assignment Help', 'Need guidance on submitting the first assignment.', 3, 4);

-- Sample Forum Replies
INSERT INTO public.forum_reply (reply_body, post_id, account_id)
VALUES
('Thanks for sharing this research.', 1, 2),
('I will review the policy document.', 2, 4),
('Looking forward to the event.', 3, 1),
('I can help with the assignment.', 4, 4);
